name: Test and Run
on:
  push:
    paths:
      - 'hello.py' # Only trigger if hello.py is modified

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Syntax Check (The Test)
        run: python -m py_compile hello.py # Checks for indentation or syntax errors

      - name: Run Script
        run: python hello.py
